export const govtJobs = [
    {
        id: 1,
        title: "Assistant Engineer",
        department: "Public Works Department",
        location: "Kolkata, West Bengal",
        qualification: "B.E/B.Tech in Civil Engineering",
        lastDate: "2024-12-31",
    },
    {
        id: 2,
        title: "Primary Teacher",
        department: "Education Department",
        location: "Gangarampur, West Bengal",
        qualification: "D.El.Ed/B.Ed",
        lastDate: "2024-12-20",
    },
    {
        id: 3,
        title: "Data Entry Operator",
        department: "Health Department",
        location: "Delhi",
        qualification: "12th Pass, Basic Computer Knowledge",
        lastDate: "2024-12-25",
    },
    {
        id: 4,
        title: "Junior Clerk",
        department: "Municipal Corporation",
        location: "Mumbai, Maharashtra",
        qualification: "Graduation in Any Discipline",
        lastDate: "2025-01-05",
    },
    {
        id: 5,
        title: "Police Constable",
        department: "Police Department",
        location: "Bangalore, Karnataka",
        qualification: "10th Pass",
        lastDate: "2024-12-15",
    },
    {
        id: 6,
        title: "Staff Nurse",
        department: "Health Department",
        location: "Chennai, Tamil Nadu",
        qualification: "Diploma/B.Sc in Nursing",
        lastDate: "2024-12-30",
    },
    {
        id: 7,
        title: "Forest Guard",
        department: "Forest Department",
        location: "Ranchi, Jharkhand",
        qualification: "12th Pass",
        lastDate: "2024-12-28",
    },
    {
        id: 8,
        title: "Revenue Inspector",
        department: "Revenue Department",
        location: "Lucknow, Uttar Pradesh",
        qualification: "Graduation in Commerce",
        lastDate: "2024-12-22",
    },
    {
        id: 9,
        title: "Junior Engineer",
        department: "Railways",
        location: "Delhi",
        qualification: "Diploma/B.E in Engineering",
        lastDate: "2025-01-10",
    },
    {
        id: 10,
        title: "Agricultural Officer",
        department: "Agriculture Department",
        location: "Patna, Bihar",
        qualification: "B.Sc in Agriculture",
        lastDate: "2024-12-27",
    },
    {
        id: 11,
        title: "Clerk",
        department: "Banking Department",
        location: "Hyderabad, Telangana",
        qualification: "Graduation in Any Discipline",
        lastDate: "2024-12-18",
    },
    {
        id: 12,
        title: "Accountant",
        department: "Finance Department",
        location: "Ahmedabad, Gujarat",
        qualification: "B.Com/M.Com",
        lastDate: "2024-12-29",
    },
];

console.log(govtJobs);
